---
# ArchLinux-specific package tasks for elasticsearch

- include_vars: arch.yml

- name: Install elasticsearch
  pacman:
    name: "{{ item }}"
    state: installed
  with_items:
    "{{ elasticsearch_packages }}"
