---
# Debain-specific package tasks for elasticsearch

- include_vars: debian.yml

- name: Install https driver for APT
  apt:
    name: apt-transport-https
    state: installed

- name: Install elasticsearch repository
  apt_repository:
    repo: "deb {{ elasticsearch_repository.url }} {{ elasticsearch_repository.type }}"
    filename: elasticsearch
    state: present

- name: Install elasticsearch GPG key
  apt_key:
    url: "{{ elasticsearch_gpg_key }}"
    state: present

- name: Install elasticsearch
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    "{{ elasticsearch_packages }}"
