---
# plugin installation tasks for elasticsearch

# Make sure the configuration is reloaded (if required) before continuing
- meta: flush_handlers

- name: Wait for ElasticSearch to start
  wait_for:
    host: "{{ elasticsearch_bind }}"
    port: "{{ elasticsearch_port_http }}"
    delay: 1

- name: Install plugins in ElasticSearch
  command: >
    /usr/share/elasticsearch/bin/plugin install "{{ item }}"
  args:
    creates: "/usr/share/elasticsearch/plugins/{{ item }}"
  ignore_errors: true
  with_items:
    "{{ elasticsearch_plugins_add }}"
  notify:
    restart elasticsearch

- name: Remove plugins from ElasticSearch
  command: >
    /usr/share/elasticsearch/bin/plugin remove "{{ item }}"
  args:
    removes: "/usr/share/elasticsearch/plugins/{{ item }}"
  ignore_errors: true
  with_items:
    "{{ elasticsearch_plugins_remove }}"
  notify:
    restart elasticsearch
