---
# plugin installation tasks for elasticsearch

# Make sure the configuration is reloaded (if required) before continuing
- meta: flush_handlers

- name: Wait for ElasticSearch to start
  wait_for:
    host: "{{ elasticsearch_bind }}"
    port: "{{ elasticsearch_port_http }}"
    delay: 1
