---
# RedHat-specific package tasks for elasticsearch

- include_vars: redhat.yml

- name: Install elasticsearch repository
  yum_repository:
    name: elasticsearch
    description: ElasticSearch Repository
    file: elasticsearch
    baseurl: "{{ elasticsearch_repository.url }}"
    gpgkey: "{{ elasticsearch_gpg_key }}"
    gpgcheck: yes

- name: Install elasticsearch
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    "{{ elasticsearch_packages }}"
